services:
  bitwarden-mxroute-server:
    container_name: bitwarden-mxroute-server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "6123:6123"
    env_file: .env.prod
  bitwarden-mxroute-web:
    container_name: bitwarden-mxroute-web
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "6124:6124"
    env_file: .env.prod
    depends_on:
      - bitwarden-mxroute-server
