services:
  mxroute-bitwarden:
    image: ghcr.io/bfpimentel/mxroute-bitwarden:latest
    ports:
      - "5000:5000"
    environment:
      - MXROUTE_SERVER=your_server
      - MXROUTE_USERNAME=your_username
      - MXROUTE_API_KEY=your_api_key
